apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nj7tfzswr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nj7tfzswr-python 
  name: nj7tfzswr-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nj7tfzswr-python
    weight: 100 
