apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nj7tfzswr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nj7tfzswr-python 
  name: nj7tfzswr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nj7tfzswr-python 
