apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nj7tfzswr-python 
  janus-idp.io/tekton: nj7tfzswr-python
  backstage.io/kubernetes-id: nj7tfzswr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nj7tfzswr-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml